# Generated by Django 2.0.5 on 2018-05-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('To_Do_App', '0002_auto_20180502_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
